### ISSUE TITLE
Time Tracking

### ISSUE THREAD

**Issue by Jacohun1** [CodePunisher123/Domain_Checker#1]
Can you make a way to track each sub-domain over a length of time? Like an option to make a log file every month? #

**Comment by CodePunisher123** [comment]
I have thought about implementing an option for /Join <site> <timeframe> yes, I just haven't figured out quite yet how to approach it.

**Comment by Jacohun1** [comment]
What if for each unique join you timestamped it? Then you could call back based on a date like the last 7 days, month, few months. Maybe have the storage files generated by joins in a month?

**Comment by Jacohun1** [comment]
You're the best!
